#!/bin/sh

if [ $# -ne 2 ]
then
    echo "Usage: `basename $0` SourceDir HeaderFile"
    exit 1
fi

SRC=$1
FILE=$2

function putline
{
    echo -e $1 >> $FILE
}

touch $FILE

putline "#ifndef A2X_H"
putline "#define A2X_H"
putline ""

for f in $SRC/a2x_*.p.h
do
	putline "#include \"../src/`basename $f`\""
done

putline ""
putline "#endif // A2X_H"

GEANY_TAGS_DIR=~/.geany/tags

if [ -d $GEANY_TAGS_DIR ]
then
    sync
    INC_FILE="`readlink -f $FILE`"
    echo "Writing Geany tags file"
    geany -g $GEANY_TAGS_DIR/a2x.c.tags $INC_FILE
fi

exit 0
