#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: `basename $0` HeaderFile"
    exit 1
fi

FILE="`readlink -f $1`"

geanytags()
{
    if [ -d $1 ]
    then
        geany -g $1/a2x.c.tags $FILE
    fi
}

geanytags "~/.geany/tags"
geanytags "~/.config/geany/tags"

exit 0
