#!/bin/bash

if [ $# -ne 1 ]
then
    echo "Usage: $(basename $0) ProjectPath"
    exit 1
fi

A2X_LOCATION=$(readlink -f $(dirname $0)/..)
echo "Found a2x: $A2X_LOCATION"

PROJECT_NAME=$(basename $1)
PROJECT_PATH=$1

FILE=

if [ -e $PROJECT_PATH ]
then
    echo "Error: \"$PROJECT_NAME\" already exists"
    exit 1
fi

newdir()
{
    echo "Making dir: $1"
    mkdir $1
}

newfile()
{
    echo "Writing file: $1"
    FILE=$1
    touch $FILE
}

putline()
{
    TABS=

    for i in $(seq 1 $1)
    do
        TABS=$TABS"\040\040\040\040"
    done

    echo -e $TABS$2 >> $FILE
}

newdir "$PROJECT_PATH"
newdir "$PROJECT_PATH/make"
newdir "$PROJECT_PATH/src"

newfile "$PROJECT_PATH/make/Makefile"
putline 0 "APP = $PROJECT_NAME"
putline 0 "TARGET_DIR = .."
putline 0 "SRC_DIR = ../src"
putline 0 "GFX_DIR ="
putline 0 "SFX_DIR ="
putline 0 "A2X_PATH = $A2X_LOCATION"
putline 0 "include \$(A2X_PATH)/make/project/Makefile.linux"

newfile "$PROJECT_PATH/src/main.c"
putline 0 "#include <a2x.h>"
putline 0 ""
putline 0 "void a2x(void)"
putline 0 "{"
putline 1 "    a2x_set(\"title\", \"New App\");"
putline 1 "    a2x_set(\"version\", \"0.1\");"
putline 1 "    a2x_set(\"author\", \"You\");"
putline 1 "    a2x_set(\"window\", \"no\");"
putline 1 "    a2x_set(\"quiet\", \"yes\");"
putline 0 "}"
putline 0 ""
putline 0 "void Main(void)"
putline 0 "{"
putline 1 "    printf(\"Code me!\\\n\");"
putline 0 "}"

echo "$PROJECT_NAME is ready!"

exit 0
